### ISSUE TITLE
Better library name and API

### ISSUE THREAD

**Issue by austencollins** [serverless/aws-sdk-extra#4]
Suggestions to a few problems I encountered using the first version of this:

**Calling it `aws-sdk` is confusing.  It doesn't indicate that this is different or contains extra value**

I suggest we rename this to `aws-sdk-extra`, alike `fs-extra`

**Putting everything under `utils` is a bad practice**

My use-case was using this w/ 2 different accounts in AWS lambda which caches the SDK for a few minutes until the container is killed.

Having to rely on `AWS.config.update()` made this nearly impossible to do, as this sets credentials globally for everything.  Generally, the best practice with the SDK is to create instances of the Service classes (e.g. CloudWatch()) and pass credentials and regions into there.  

Lastly, the namespace `utils` is a bit common and we don't want to occupy something AWS might use.

I propose we use the name `Extras` and turn that into a class, which alike all other AWS Service classes, you can instantiate w/ `credentials`, `region`, etc., enabling users to make multiple instances of this.

`const awsExtras = AWS.Extras({ credentials, region }) // This should take the same config as any other service class`

`awsExtras.getMetrics()`

**Comment by eahefnawy** [comment]
> Calling it aws-sdk is confusing. It doesn't indicate that this is different or contains extra value

You missed the `@serverless/` prefix 😝 ... that's the value. It's serverless.

> Putting everything under utils is a bad practice

Why is it a bad practice? 🤔 ... putting everything under `Extras` doesn't seem too different. Or is it about the name?

> My use-case was using this w/ 2 different accounts in AWS lambda which caches the SDK for a few minutes until the container is killed.

> Having to rely on AWS.config.update() made this nearly impossible to do, as this sets credentials globally for everything. Generally, the best practice with the SDK is to create instances of the Service classes (e.g. CloudWatch()) and pass credentials and regions into there.

That is a good point, I haven't thought about that edge case. I've thought about `new AWS.Utils()` before to follow the service pattern, but that extra instance initialization step turned me off. I liked being able to require and call functions directly. It also didn't resonate with me considering that most of the functions interact with multiple services. I wasn't able to think of these functions as single entities that you can initialize.

So I think we should do as you suggested to allow for the use case you posted.

How about `const awsServerless = new AWS.Serverless({ credentials, region })` though? 😄 

Well I guess Serverless is too common now, and I wouldn't be surprised if the `aws-sdk` introduced a new "Serverless" service/class. I just love our brand so much and don't want to let it go ⚡ ❤️

**Comment by austencollins** [comment]
I might also be detecting some issues because the SDK is cached globally w/ credentials in stateless compute, which is being reused.  Likely a potential big security risk here.

I still think the `aws-sdk-extra` makes sense `aws-sdk` doesn't indicate to the user that the library is different in any way.  It's not immediately clear what `@serverless/aws-sdk` is other than perhaps a fork to submit a fix to the normal `aws-sdk`?  I still htink the `aws-sdk-extra` and `AWS.Extra(config)` is a simple clear solution for this.

**Comment by eahefnawy** [comment]
Done
